# Generated by Django 2.1 on 2018-08-22 02:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(default=10)),
                ('width', models.IntegerField(default=10)),
                ('bomb_count', models.IntegerField(default=10)),
                ('state', models.CharField(default='ready', max_length=200)),
                ('last_move', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last move')),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_loc', models.IntegerField(default=0)),
                ('y_loc', models.IntegerField(default=0)),
                ('bomb', models.BooleanField(default=False)),
                ('flagged', models.BooleanField(default=False)),
                ('discovered', models.BooleanField(default=False)),
                ('mine_count', models.IntegerField(default=0)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Board')),
            ],
        ),
    ]
