# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-25 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='state',
            field=models.CharField(default='active', max_length=200),
        ),
    ]
